### ISSUE TITLE
Folder Sort fatal exception after sorting file with non-latin name

### ISSUE THREAD

**Issue by nikramakrishnan** [nikramakrishnan/system-cleaner#1]
Folder Sort stops with an exception when the directory currently being sorted has a file with non-latin file name.
**Error** -
```python
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python35-32\lib\tkinter\__init__.py", line 1550, in __call__
    return self.func(*args)
  File "F:\Nik\Github\Folder Sort\folder_sort_GUI.py", line 234, in askdirectory
    self.FolderSort(directory)
  File "F:\Nik\Github\Folder Sort\folder_sort_GUI.py", line 306, in FolderSort
    rep.insert([file,os.getcwd(),(os.getcwd()+'\\'+'Documents')],res)
  File "F:\Nik\Github\Folder Sort\report.py", line 99, in insert
    print("<tr>\n\t<td>"+str(self.recs+1)+"</td>\n\t<td>"+data[0]+"</td>\n\t<td>"+data[1]+"</td>\n\t<td>"+data[2]+"</td>\n</tr>\n",file=self.f)
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 25-28: character maps to <undefined>
```

Operating System - Windows 10
Python Version - 3.5.2

**Comment by nikramakrishnan** [comment]
The issue is in report.py.
The file insert is not able to encode the character. Adding encoding to the file open line should fix this.
The HTML file should also have a meta tag to declare the file UTF-8.

**Comment by nikramakrishnan** [comment]
Fixed. #2
